<P>YOU HAVE BEEN DIRECTED TO THIS FORM AS YOUR DEVICE IS HAVING DIFFICULTY LOADING OUR LABEL CREATOR PRESENTLY. YOU CAN ORDER VIA THIS FORM OR EVEN SEND US A MESSAGE AT BOTTOM OF FORM</P>
<P>THANKS </P>
<P><A title="BACK UP ORDER FORM" href="http://form.jotformpro.com/form/23563338090958"><FONT color=#562bac>BACK UP LABEL ORDER FORM</FONT></A></P>
<P>&nbsp;</P>