<P align=center><STRONG>CURRENT&nbsp;DISPATCH 4 BUSINESS DAY&nbsp; FOR EXPRESS (LABELS ONLY) , LABEL ORDERS &nbsp;5-7 DAYS</STRONG></P>
<P align=center><STRONG>ALL GIFT PRODUCTS (NON LABEL PRODUCTS )&nbsp; 7-10 BUSINESS DAYS. ORDER PLACED NOW WILL BE DISPATCHED THE FIRST WEEK OF JANUARY.</STRONG></P>
<P align=center><STRONG><FONT color=#d72b2b size=5>IDENTIKID IS CLOSED DEC 15TH - JANUARY 5TH 2015&nbsp;.</FONT></STRONG></P>
<P align=center><STRONG><FONT color=#d72b2b size=5>ORDERS PLACED DURING THIS PERIOD WILL BE DISPATCHEDIN THE FIRST WEEK OF JANUARY...ALLOW TRANSIT TO YOUR REGION FROM NSW</FONT></STRONG></P>
<P align=center><STRONG><FONT color=#d72b2b size=5></FONT></STRONG>&nbsp;</P>
<P align=center><STRONG><FONT color=#d72b2b size=5>..MERRY XMAS..</FONT></STRONG></P>
<P align=center><FONT size=5></FONT>&nbsp;</P>