<strong></strong>
<p align="center"><br><font face="Verdana" size="4"><font size="2"></font></font></p><font face="Verdana" size="4"><font size="2"><p align="center"><font color="#ff002b" size="4">WE ARE NOW CLOSED UNTIL THE 5TH JANUARY.</font> </p><p align="center">SEE SHIPPING TIMES FOR TURNAROUND...ORDER PLACED</p><p align="center">DURING CLOSURE WILL BEGIN PROCESSING ON THE 5TH JANUARY AND WILL BE </p><p align="center">SHIPPED AS PER SHIPPING TIMES. NO ORDERS WILL BE DISPATCHED PRIOR TO RETURN . </p><p align="center">NO CUSTOMER SERVICE WILL BE AVAILABLE DURING&nbsp;CLOSURE</p><p align="center"><br></p></font><p align="center"><br></p></font><p align="center"><font face="Verdana" size="4"><font size="2"><br></font></font></p><p align="center"><font face="Verdana" size="4"><font size="2">This email is confirming your order has arrived at the identikid office. If your order has been mailed, faxed or submitted online this confirms it has now arrived at our ordering dept. The order will be commenced on the date of payment has arrived at identikid. Allow up to 48 hours for direct debits. Credit Card and Paypal are usually immediate.</font></font></p>
<p align="center"><font face="Verdana" size="4"><font size="2">Please refer to our&nbsp;<font color="#002bd7" size="3"> </font><a href="http://identikid.com.au/pages/Shipping"><font color="#002bd7" size="3">SHIPPING</font></a><font color="#002bd7" size="3">&nbsp;</font> for current turnaround times. This can vary due to seasonal demands.</font></font></p>
<p align="center"><font size="2"><font face="Verdana">&nbsp;<font size="1">FOR MORE DETAILS ON SHIPPING, REFUNDS AND ERROR POLICY CLICK ON LINKS BELOW . PLEASE </font></font></font><font size="1"><font face="Verdana"><strong>DOUBLE CHECK THE ORDER ABOVE</strong> AND ENSURE ALL DETAILS ARE CORRECT AS THIS IS HOW IT WILL BE PRODUCED. ERRORS WILL BE PRINTED IF NOT NOTIFIED. IF YOU TYPE IN CAPS IT IS PRINTED IN CAPS. CHECK SPELLING AND PHONE NOS...ERRORS BY PERSON ENTERING ARE NOT REFUNDABLE.</font></font></p><span class="Apple-style-span" style="font:/normal Verdana; color: rgb(0, 0, 0); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; white-space: normal; border-collapse: separate; orphans: 2; widows: 2; font-size-adjust: none; font-stretch: normal; -webkit-border-horizontal-spacing: 0px; -webkit-border-vertical-spacing: 0px; -webkit-text-decorations-in-effect: none; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;"><span class="Apple-style-span" style="color: rgb(99, 100, 102); line-height: 20px; font-family: verdana, arial, helvetica, sans-serif; font-size: 15px;"><strong><a href="http://identikid.com.au/pages/Shipping">
</a></strong><p><strong><a href="http://identikid.com.au/pages/Shipping"></a>
<table width="871" height="28" style="width: 871px; height: 28px;" border="0">
<tbody>
<tr>
<td>
<p align="center"><font color="#002bd7">&nbsp;&nbsp;&nbsp;&nbsp;</font><font color="#002bd7"><a href="http://identikid.com.au/pages/Shipping"><font color="#002bd7">SHIPPING</font></a></font><font color="#002bd7">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </font></p></td>
<td>
<p align="center"><a href="http://identikid.com.au/Home/Payment_information_and_details"><font color="#002bd7">PAYMENT DETAILS</font></a></p></td>
<td>
<p align="center"><a href="http://identikid.com.au/Home/Refunds,_Terms_and_Conditions_of_sale"><font color="#002bd7">TERMS AND CONDITIONS</font></a></p></td>
<td>
<p align="center"><font color="#0000ac"></font>&nbsp;</p></td></tr></tbody></table></strong></p>
<p><font face="Verdana" size="2"></font>&nbsp;</p>
<p><font face="Verdana" size="2">Any further queries or anything that you dont understand please feel free to call or email for assistance <a href="mailto:info@identikid.com.au">info@identikid.com.au</a>.</font></p>
<p><font face="Verdana" size="2">ANY URGENT CONTACT IS BEST BY EMAIL AS CHECKED REGULARLY. . PAYMENT BY PHONE OR&nbsp;ERRORS FOUND&nbsp;LEAVE A MESSAGE AND WE WILL RETURN YOUR CALL. IF YOU DO FIND AN ERROR PLEASE EMAIL ASAP AS WE OFTEN WORK OUT OF REGULAR BUSINESS HOURS AND CAN ADJUST ORDERS IF NEEDED</font></p>
<p><font face="Verdana" size="2">ANY FURTHER QUERIES PLEASE CONTACT US </font></p>
<p><font face="Verdana" size="2">IDENTIKID CUSTOMER SERVICE </font></p>
</span></span>