<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"><STRONG><FONT color=#373737 size=2>&nbsp;</FONT></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"><STRONG>Throughout the year our turnaround can vary due to seasonality..We always dispatch as quickly as possible to all our customers. Year round dispatch is as below.</STRONG></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"><STRONG><FONT color=#ff0056>Currently our Xpress service is dispatched in 3 business day from Wagga NSW It is sent via Express Post at Aust Post , this is the quickest way to get your order. You must allow for transit time for your order from NSW.</FONT></STRONG></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"><STRONG><FONT color=#ff0056>Normal postage (LABELS AND TAGS) 5 days dispatch from Wagga NSW on all other orders...then allow normal transit time.</FONT></STRONG></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"><STRONG><FONT color=#ff0056>NON LABEL PRODUCT Dispatched in 5 days on any non-label product then allow normal postage transit times</FONT></STRONG></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"><FONT face=Verdana><FONT size=2><STRONG><FONT color=#8100ff size=3><U>NORMAL POST</U></FONT> </STRONG></FONT></FONT></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"><STRONG><FONT size=2><U><FONT color=#812bff>Labelling Product</FONT></U> -</FONT></STRONG><FONT color=#5c5c5c><FONT face=Verdana><FONT size=2>Orders are dispatched from NSW within<STRONG> 3-5 days</STRONG> from date of <STRONG>payment</STRONG> is received at office. Business days are Monday-Friday. <STRONG>Public Holidays and Postal holidays</STRONG> can affect these times due to austpost closure. Allow Aust Post normal for transit time depending on your region (1-2 days for capital cities and longer for regional and remote areas. Sent via Australia Post</FONT></FONT><FONT face=Verdana><FONT size=2> . <STRONG>$3.00 per order.</STRONG></FONT></FONT></FONT></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"><FONT face=Verdana><FONT size=2><STRONG><FONT color=#562bff><U>Non- Label Product</U> </FONT>(Parcel Post items)- </STRONG></FONT></FONT><FONT color=#5c5c5c><FONT face=Verdana><FONT size=2>Orders are dispatched from NSW within<STRONG> 3-5</STRONG> days from date of <STRONG>payment</STRONG> is received at office. Business days are Monday-Friday. <STRONG>Public Holidays and Postal holidays</STRONG> can affect these times due to austpost closure. Allow Mormal Aust Post for transit time depending on your region (1-2 days for capital cities and longer for regional and remote areas. Sent via Australia Post</FONT></FONT><FONT face=Verdana><FONT size=2> . <STRONG>$7.50 per order.</STRONG> This is the postal charge for parcel post via Aust Post.</FONT></FONT></FONT></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"><FONT color=#562bff><U><STRONG>Large Items</STRONG></U></FONT> - ie <STRONG>Backpack $10.00. </STRONG>Postage Noted on checkout. The price is determined by Aust Post item weight restrictions &gt;500g. </P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px" align=justify><FONT color=#8100ff><FONT face=Verdana><FONT size=2><STRONG><U><FONT size=3>EXPRESS SERVICE</FONT></U></STRONG> </FONT></FONT></FONT><FONT color=#8100ff><FONT face=Verdana><FONT size=2><FONT color=#3d3d3d>$15.00 per order. Australia Wide Dispatched from our office within 3 business days. Allow TRANSIT for Delivery of items and transit time(Regional and Remote allow Australia post normal times). </FONT></FONT></FONT></FONT><FONT color=#8100ff><FONT face=Verdana><FONT size=2><FONT color=#3d3d3d>This service is fully trackable via Australia Post express service. </FONT></FONT></FONT></FONT></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px" align=justify><FONT color=#ff2b56 size=2 face=Verdana><STRONG>D</STRONG></FONT><FONT face=Verdana><FONT size=2><FONT color=#ff2b56><STRONG>irect debits can take up to 48 hours for payment to appear so best to pay via c/card for a speedy dispatch!</STRONG></FONT> </FONT></FONT></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px" align=justify></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px" align=justify><STRONG><FONT color=#562bff><U>OUTSIDE AUSTRALIA</U></FONT></STRONG></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px" align=justify><FONT size=2 face=Verdana><FONT color=#812bac><STRONG>Overseas orders</STRONG></FONT> - <STRONG>Labels only and small gift items.</STRONG></FONT></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px" align=justify><FONT size=2 face=Verdana><STRONG>Regular Service 15.00 AUD via Airmail -10-14 days for delivery. Large items for postage overseas, ie non label order please email for quote on postage.</STRONG></FONT></P>
<P><FONT color=#373737 size=2 face=Verdana><FONT color=#8100d7><STRONG>Xpress Delivery Overseas</STRONG></FONT> $55.00 AUD Allow up to 4-7 business days to most countries. Fully trackable</FONT></P></STRONG>