<P style="COLOR: rgb(99,100,102); PADDING-BOTTOM: 0px; PADDING-TOP: 20px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px; font-size-adjust: none; font-stretch: normal"><STRONG>Throughout the year our turnaround can vary due to seasonality..We always dispatch as quickly as possible to all our customers. Online orders begin processing immediately, overnight order commence from 8am. Phone order allow extra&nbsp;2 days onto times below.&nbsp;Dispatch is the day they leave our office, then allow normal Aust post service times.</STRONG></P>
<P style="COLOR: rgb(99,100,102); PADDING-BOTTOM: 0px; PADDING-TOP: 20px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px; font-size-adjust: none; font-stretch: normal"><FONT face=Verdana><FONT size=2><STRONG><FONT color=#8100ff size=3><U>NORMAL POST</U></FONT> </STRONG></FONT></FONT></P>
<P style="COLOR: rgb(99,100,102); PADDING-BOTTOM: 0px; PADDING-TOP: 20px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px; font-size-adjust: none; font-stretch: normal"><STRONG><FONT size=2><U><FONT color=#812bff>Labelling Product</FONT></U> -</FONT></STRONG><FONT color=#5c5c5c><FONT face=Verdana><FONT size=2> Business days are Monday-Friday. <STRONG>Public Holidays and Postal holidays</STRONG> can affect these times due to austpost closure. Allow Aust Post normal for transit time depending on your region (1-2 days for capital cities and longer for regional and remote areas. Sent via Australia Post</FONT></FONT><FONT face=Verdana><FONT size=2> . <STRONG>$3.00 per order.</STRONG></FONT></FONT></FONT></P>
<P style="COLOR: rgb(99,100,102); PADDING-BOTTOM: 0px; PADDING-TOP: 20px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px; font-size-adjust: none; font-stretch: normal"><FONT face=Verdana><FONT size=2><STRONG><FONT color=#562bff><U>Non- Label Product</U> </FONT>(Parcel Post items)- </STRONG></FONT></FONT><FONT color=#5c5c5c><FONT face=Verdana><FONT size=2>Business days are Monday-Friday. <STRONG>Public Holidays and Postal holidays</STRONG> can affect these times due to austpost closure. Allow Mormal Aust Post for transit time depending on your region (1-2 days for capital cities and longer for regional and remote areas. Sent via Australia Post</FONT></FONT><FONT face=Verdana><FONT size=2> . <STRONG>$7.50 per order.</STRONG> This is the postal charge for parcel post via Aust Post.</FONT></FONT></FONT></P>
<P style="COLOR: rgb(99,100,102); PADDING-BOTTOM: 0px; PADDING-TOP: 20px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px; font-size-adjust: none; font-stretch: normal"><FONT color=#562bff><U><STRONG>Large Items</STRONG></U></FONT> - ie <STRONG>Backpack $10.00. </STRONG>Postage Noted on checkout. The price is determined by Aust Post item weight restrictions &gt;500g. </P>
<P style="COLOR: rgb(99,100,102); PADDING-BOTTOM: 0px; PADDING-TOP: 20px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px; font-size-adjust: none; font-stretch: normal"></P>
<P style="COLOR: rgb(99,100,102); PADDING-BOTTOM: 0px; PADDING-TOP: 20px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px; font-size-adjust: none; font-stretch: normal" align=justify><FONT color=#8100ff><FONT face=Verdana><FONT size=2><FONT color=#3d3d3d></FONT></FONT></FONT></FONT>&nbsp;</P>
<P style="COLOR: rgb(99,100,102); PADDING-BOTTOM: 0px; PADDING-TOP: 20px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px; font-size-adjust: none; font-stretch: normal" align=justify><STRONG><FONT color=#562bff><U>OUTSIDE AUSTRALIA</U></FONT></STRONG></P>
<P style="COLOR: rgb(99,100,102); PADDING-BOTTOM: 0px; PADDING-TOP: 20px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px; font-size-adjust: none; font-stretch: normal" align=justify><FONT size=2 face=Verdana><FONT color=#812bac><STRONG>Overseas orders</STRONG></FONT> - <STRONG>Labels only and small gift items.</STRONG></FONT></P>
<P style="COLOR: rgb(99,100,102); PADDING-BOTTOM: 0px; PADDING-TOP: 20px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px; font-size-adjust: none; font-stretch: normal" align=justify><FONT size=2 face=Verdana><STRONG>Regular Service 15.00 AUD via Airmail -10-14 days for delivery. Large items for postage overseas, ie non label order please email for quote on postage.</STRONG></FONT></P>
<P><FONT color=#373737 size=2 face=Verdana><FONT color=#8100d7><STRONG>Xpress Delivery Overseas</STRONG></FONT> $55.00 AUD Allow up to 4-7 business days to most countries. Fully trackable</FONT></P>