<H2 align=center><FONT size=3><FONT color=#d72b2b size=4>
<P align=center><STRONG>SEE SHIPPING FOR CURRENT TURNAROUND AND POSTAGE&nbsp;PRICING.</STRONG></P>
<P align=center><STRONG>CURRENT ORDERS ARE DISPATCHED IN 5-7 DAYS...FROM THE PAYMENT DATE OF ORDER.</STRONG></P>
<P align=center>ALLOW NORMAL POSTAGE TIMES FROM NSW. SH</P>
<P align=center><STRONG></STRONG></FONT>&nbsp;</P></FONT></H2>