<H2 align=center><FONT size=3>
<P align=center><STRONG><FONT size=4>CURRENT&nbsp;DISPATCH 4 BUSINESS DAY&nbsp; FOR EXPRESS (LABELS ONLY) , LABEL ORDERS &nbsp;5-7 DAYS</FONT></STRONG></P>
<P align=center><STRONG><FONT size=4>ALL GIFT PRODUCTS (NON LABEL PRODUCTS )&nbsp; 7-10 BUSINESS DAYS</FONT></STRONG></P>
<P align=center><STRONG><FONT size=4>XMAS ORDERS MUST BE PLACED BY THE <FONT color=#d7002b>10TH DECEMBER</FONT>...XP TURNAROUND ON NON LABEL PRODUCTS IS NORMAL DISPATCH TIME ...SENT BY XP POST. ORDERS PLACED AFTER 10TH DEC MAY NOT BE RECIEVED BEFORE THE NEW YEAR DUE TO POSTAL DELAYS.</FONT></STRONG></P>
<P align=center><STRONG><FONT color=#d72b2b size=4>IDENTIKID IS CLOSED DEC 15TH - JANUARY 5TH 2015&nbsp;.</FONT></STRONG></P>
<P align=center><STRONG><FONT color=#d72b2b size=4>ORDERS PLACED DURING THIS PERIOD WILL BE PROCESSED AND DISPATCHED AFTER THE 9TH JANUARY..MERRY XMAS....</FONT></STRONG></P></FONT><FONT size=4>&nbsp;&nbsp;&nbsp;</FONT></H2>