<H2 align=center>&nbsp;BACK TO SCHOOL 2012 
<H2></H2>
<P align=center><FONT color=#ff0056 size=2>ONLINE&nbsp;ORDERS FASTEST DISPATCH AND PROCESSED <STRONG>WITHOUT DELAY</STRONG>.</FONT></P>
<P align=center><FONT size=2>&nbsp;ALL&nbsp;<STRONG><FONT color=#ff0056>LABEL</FONT> ORDERS</STRONG>&nbsp;PLACED VIA WEB WILL BE </FONT><FONT size=2>DISPATCHED IN</FONT></P>
<P align=center><FONT size=2><STRONG>3 &nbsp;BUSINESS DAYS.&nbsp;&nbsp; OTHER PRODUCT ALLOW UP TO 5 DAYS.&nbsp;</STRONG></FONT><FONT size=2><STRONG>&nbsp;</STRONG></FONT></P>
<P align=center><FONT size=2><STRONG>&nbsp;</STRONG></FONT><FONT size=2>ALL <STRONG>GIFT / NON LABEL ORDERS</STRONG> AND ORDERS </FONT><FONT size=2>PLACED <STRONG>BY PHONE ,FAX OR MAIL</STRONG></FONT></P>
<P align=center><FONT size=2>&nbsp;ALLOW <STRONG>5-7 BUSINESS DAYS. PHONE 1300 133949 OR 0269212888.</STRONG></FONT></P>
<P align=center><FONT size=2>EXPRESS ORDERS DISPATCHED WITHIN 48 HOURS&nbsp;FROM PAYMENT</FONT><FONT size=2>&nbsp;RECIEVED .&nbsp;</FONT></P>
<P align=center><FONT size=2>EXPRESS DELIVERY&nbsp;FEE 9.50 (FULLY TRACKABLE)</FONT></P>
<P align=center><FONT size=2>&nbsp;ALLOW TRANSIT COURIER&nbsp; </FONT><FONT size=2>2-3 &nbsp;BUSINESS DAYS TO YOUR REGION</FONT></P>
<P align=center><FONT color=#ff00ac size=2>THE EXPRESS SERVICE CAN BE TRACKED ONLINE WITH YOUR BOOKING CODE WHICH</FONT></P>
<P align=center><FONT color=#ff00ac size=2>IS EMAILED TO YOU AT TIME OF DISPATCH FROM OUR PREMISES</FONT></P>
<P align=center><FONT size=2>*business days do not include weekend or public holiday</FONT></P>
<P align=center><FONT color=#0000d7 size=2>AUSTRALIA DAY HOLIDAY 26TH JANUARY ALL POSTAL AND COURIER SERVICES CLOSED SO NO PRODUCTS WILL BE DISPATCHED ON THAT DAY. IDENTIKID WILL CLOSE FOR 26TH JANUARY ONLY.</FONT></P></H2>