<FONT color=#fcfcfc>identikids Name labels are offers a range of kid friendly name labels and name tags and kids personalised products that are practical, high quality,innovative and fun. Our name labels are also a fabulous and simple no fuss fundraising opportunity and will save your group/school, parents and kids&nbsp;time and money. Our name labels are trusted by Mums everywhere and our huge amount of repeat business shows how our customers value our quality.</FONT> 
<P><FONT color=#fcfcfc>identikid offer an ever growing range of kids name labels which can be&nbsp;securely purchased online. If you need name labels for your children's clothing &amp; property then take a look through our fantastic&nbsp;and affordable labelling ideas. </FONT>
<P><FONT color=#fcfcfc>Our name labels and name tags are 100% guaranteed* and we pride ourselves on&nbsp;a huge amount of repeat business.&nbsp;Our product is superior&nbsp;in terms of quality, service and pricing. identikid have proven to be a perfect fundraising idea and with commission up to 25% with no set-up cost to your fundraiser it couldnt be easier. </FONT>
<P><FONT color=#fcfcfc>Design your own labels online, with a choice of fonts,colours and pictures. All identikid name labels and tags&nbsp;are high quality, attractive and very easy to use. Fundraising is&nbsp;simple with identikid name labels because we deliver the name labels directly to your customers so they get them fast and the work is done for you. </FONT>
<P><FONT color=#fcfcfc>identikid is your first choice for school name labels and back to school kids personalised products. We offer a great range of personalised bags for school use. Kid-tough sturdy washable drawstring and shoulder bags for library and sports. XL Kindergarten Bags, great for preschool use for linen etc. Our library bags are 100% cotton in pink,black,denim and natural with choice of picture and add name or wording. Every child deserves a fantastic library bag from identikid. High quality black Mesh personalised swimming bags. Personalised Shoulder Bags. Kindergarten Large Drawstring Bags are a Must for all their bedding needs </FONT>Whether back to school or kindergarten identikid's range of name labels or kids practical personalised gear will make there return to school a exciting event to look forward to. 
<P><FONT color=#fcfcfc>identikid's&nbsp;labels are very popular for fundraising, and come in an bright assortment of rainbow coloured labels or single colour choices for boys and girls. Identify your childs belonging's with name labels and tags&nbsp;for school, daycare or kindergarten. </FONT>
<P><FONT color=#fcfcfc>Use our fabulous and fun name labels on anything you do not wish to lose! Use name tags to identify toys, lunchboxes, musical instruments or sports equipment. School fundraising loves identikids product range and name labels......&nbsp;No more lost property nightmares! </FONT>
<P><FONT color=#fcfcfc>Identikid now offers a fantastic range of personalised kids gifts and unique kids gifts perfect for birthday gifts and christmas gift ideas or just for fun. See our personalised gifts page for kids gifts that are unique and fun. To find the a personalised gift for kids you cannot go past identikids great range of kids gifts and gift ideas. We have personalised kids purses, personalised kids wallets, personalised pencil cases, personalised insulated lunchboxes,personalised bags, insulated drink bottle cover and personalised and special occasion printed mugs including our Christmas mugs. Our Mugs make great Teachers gifts too..identikid offers the best and most unique gifts for everyone for all occasions. Keep an eye on our website for up to date information on special occasions. Check out our Christmas Mug designs by going to our Christmas Mug designs page. 
<P><FONT color=#fcfcfc>Our name labels can be a hassle free way of fundraising. With personalised namelabels and tags on everything that leaves the house, your child can easily locate their belongings. Children lose less&nbsp;stationery and clothing&nbsp;if you put name&nbsp;labels on their stuff.&nbsp; Identikids fantastic iron-on clothing labels are proving a real hit for parents and kids.&nbsp;Think of the amount of money in lost property one pack of labels will save in time and&nbsp;stress.&nbsp; </FONT>
<P><FONT color=#fcfcfc>By using a picture on your iron-on name tags the kids are able to recognise their own belongings before they can read. </FONT>
<P><FONT color=#fcfcfc>Our shoe labels, school bag tags, stick on labels, iron on labels and packs of assorted label are a must for all families. Add a splash of colour to the everyday with identikid and save yourself time , money and energy. </FONT>
<P><FONT color=#fcfcfc>Bags- Personalised Drawstring library bags, Natural cotton Shoulder strap bags, High Quality Mesh Bags for swimming, Generous Kindergarten Bags all in cotton canvas. Personalised bags for everyday use. Practical and personal, what a great personalised gift for kids. 
<P><FONT color=#fcfcfc>identikid's colourful range of name&nbsp;labels &amp;&nbsp;tags are perfect for everybody everyday. Check out our name bracelets and&nbsp;kids jewellery&nbsp;which is a&nbsp;BIG hit&nbsp;with the kids NOW Check out identikids wonderful Christmas sacks designed and printed in Australia. Personalised Christmas Sacks, Kids Personalised Santa Sacks that are re-usable and a memorable keepsake for years to come!&nbsp; </FONT>
<P><FONT color=#fcfcfc>identikid has personalised kids gifts galore and is your christmas gifts and santa sacks store. Great library bags and kindergarten bags for bedding. identikids personalised bags are great for all ages and high quality. </FONT>
<P>
<P></P></FONT></FONT>