<TABLE>
<TBODY>
<TR>
<TD class=maintext><FONT size=2 face="Comic Sans MS">
<P align=center><SPAN style="WIDOWS: 2; TEXT-TRANSFORM: none; TEXT-INDENT: 0px; LETTER-SPACING: normal; BORDER-COLLAPSE: separate; FONT: medium Verdana; WHITE-SPACE: normal; ORPHANS: 2; COLOR: rgb(0,0,0); WORD-SPACING: 0px; -webkit-border-horizontal-spacing: 0px; -webkit-border-vertical-spacing: 0px; -webkit-text-decorations-in-effect: none; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px" class=Apple-style-span><SPAN style="LINE-HEIGHT: 20px; FONT-FAMILY: verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); FONT-SIZE: 15px" class=Apple-style-span><FONT size=2></FONT></SPAN></SPAN>&nbsp;</P>
<P align=center><FONT face=Verdana><FONT size=2><B><FONT color=#000000><U>PAYMENT INFO</U></FONT></B></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"><B><FONT color=#000000><FONT size=2>CREDIT CARDS</FONT>&nbsp;- <FONT size=2>if processed via secure site no need to do anything further your order is underway! </FONT></FONT></B></FONT></FONT><FONT face=Verdana><FONT size=2><FONT color=#000000><B>If paying with credit card via phone. You can call 1300133949 and leave a message, we will return you call within 24 hours.</B></FONT></FONT></FONT></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px">OR</P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"><FONT face=Verdana><FONT size=2><STRONG>MONEY ORDERS&nbsp;&nbsp;post to identikid (surname/ORDER NO&nbsp;on back)<BR>PO Box 8775<BR>Wagga Wagga NSW 2650<BR>and in the name of identiBiz Pty Ltd </STRONG></FONT></FONT></P>
<P><FONT face=Verdana><FONT size=2><STRONG>PAYPAL&nbsp;Deposit to&nbsp;<A href="mailto:admin@identibiz.com">admin@identibiz.com</A>&nbsp;. Company Name identibiz pty ltd. The amount on your order. Please ensure you use your order no or surname as a reference, or we will send paypal invoice on request.</STRONG></FONT></FONT></P>
<P><FONT face=Verdana><FONT size=2><STRONG>DIRECT DEPOSIT<BR>For direct Bank Deposits (internet banking)&nbsp;or over the counter deposits you need this information. Please pay within 48 hours so we can easily match deposits.</STRONG></FONT></FONT><FONT face=Verdana><FONT size=2><BR><B>Direct Bank Account Payments (EFT Payments)</B><BR><B>Bank:</B> Westpac<BR><B>Account Name:</B> identiBiz Pty Ltd<BR><B>BSB:</B> 032-769 <BR><B>Acc. Number:</B> 277865 </FONT></FONT><FONT size=2 face=Verdana>Reference Use the <STRONG>invoice number/surname</STRONG> in the description field on the bank deposit&nbsp;Without this invoice number, we can't match your payment to your order, and this can cause delays in your order being sent out <BR></P></FONT></FONT></TD></TR></TBODY></TABLE>