<STRONG></STRONG>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"><A href="<?php echo SITE_URL;?>pages/Customer_Receipt"><IMG style="WIDTH: 162px; HEIGHT: 40px" border=0 src="/images/bg/BACK.gif" width=0 height=0></A><U><FONT face=Verdana><FONT size=2><STRONG><FONT color=#8100ff></FONT></STRONG></FONT></FONT></U></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"><U><FONT face=Verdana><FONT size=2><STRONG><FONT color=#8100ff></FONT></STRONG></FONT></FONT></U>&nbsp;</P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"><U><FONT face=Verdana><FONT size=2><STRONG><FONT color=#8100ff>NORMAL POST</FONT>&nbsp;</STRONG></FONT></FONT></U></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px"><FONT face=Verdana><FONT size=2>Orders are dispatched from NSW within&nbsp;<STRONG>5 working</STRONG> days from date of <STRONG>payment</STRONG> is received at office. Business days are&nbsp;Monday-Friday. Public Holidays and Postal holidays can affect these times due to&nbsp;austpost closure.&nbsp;&nbsp;Allow 3-5 days after dispatch for transit&nbsp;time. Sent via Australia Post</FONT></FONT><FONT face=Verdana><FONT size=2>&nbsp;. $3.00 per item</FONT></FONT></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px" align=justify><FONT color=#8100ff><FONT face=Verdana><FONT size=2><U><STRONG>EXPRESS SERVICE</STRONG></U> $15.00 Australia Wide&nbsp; Dispatched from our office within 3 business days.&nbsp;Allow up to 5 Business Days for Delivery of items and transit time. This service is fully trackable via Australia Post express service. </FONT></FONT></FONT></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px" align=justify><FONT size=2 face=Verdana>&nbsp;D</FONT><FONT face=Verdana><FONT size=2>irect debits can take up to 48 hours for payment to appear so best to pay via c/card for a speedy dispatch!&nbsp;&nbsp;</FONT></FONT></P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px" align=justify>&nbsp;</P>
<P style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 15px/20px verdana, arial, helvetica, sans-serif; COLOR: rgb(99,100,102); PADDING-TOP: 20px" align=justify><FONT size=2 face=Verdana>Overseas orders - Regular Service&nbsp;15.00 AUD&nbsp;via&nbsp;Airmail&nbsp;-10-14 days for delivery</FONT></P>
<P><FONT size=2 face=Verdana>Xpress Delivery Overseas 45.00 AUD Allow up to 4-7 business days to most countries. Fully trackable.</FONT></P>